"""base tables

Revision ID: 2f3bd55d88a
Revises: None
Create Date: 2013-04-22 15:26:47.296443

"""

# revision identifiers, used by Alembic.
revision = '2f3bd55d88a'
down_revision = None

from ansiblereport.db import JSONEncodedDict
from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('euid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('data', JSONEncodedDict(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')
    ### end Alembic commands ###
